"""Build some lists to get called."""

flaglist = ['covid', 'corona', 'h1n1', 'middle', 'acute', 'distanc',
            'isolation', 'influenza']
query_list = ['{facemask} AND {covid}',
              '{face mask} AND covid',
              '{face-mask} AND covid',
              '{N95 respirator} AND covid',
              '{FFP1} AND covid',
              '{FFP2} AND covid',
              '{FFP3} AND covid',
              '{surgical mask} AND covid',
              '{surgical grade masks} AND covid',
              '{single-use mask} AND covid',
              '{paper mask} AND covid',
              '{cloth mask} AND covid',
              '{face covering} AND covid',
              'facemask AND coronavirus',
              '{face mask} AND coronavirus',
              '{face-mask} AND coronavirus',
              '{N95 respirator} AND coronavirus',
              '{FFP1} AND coronavirus',
              '{FFP2} AND coronavirus',
              '{FFP3} AND coronavirus',
              '{surgical mask} AND coronavirus',
              '{surgical grade masks} AND coronavirus',
              '{single-use mask} AND coronavirus',
              '{paper mask} AND coronavirus',
              '{cloth mask} AND coronavirus',
              '{face covering} AND coronavirus',
              'facemask AND h1n1',
              '{face mask} AND h1n1',
              '{face-mask} AND h1n1',
              '{N95 respirator} AND h1n1',
              '{FFP1} AND h1n1',
              '{FFP2} AND h1n1',
              '{FFP3} AND h1n1',
              '{surgical mask} AND h1n1',
              '{surgical grade masks} AND h1n1',
              '{single-use mask} AND h1n1',
              '{paper mask} AND h1n1',
              '{cloth mask} AND h1n1',
              '{face covering} AND h1n1',
              'facemask AND influenza',
              '{face mask} AND influenza',
              '{face-mask} AND influenza',
              '{N95 respirator} AND influenza',
              '{FFP1} AND influenza',
              '{FFP2} AND influenza',
              '{FFP3} AND influenza',
              '{surgical mask} AND influenza',
              '{surgical grade masks} AND influenza',
              '{single-use mask} AND influenza',
              '{paper mask} AND influenza',
              '{cloth mask} AND influenza',
              '{face covering} AND influenza',
              'facemask AND {severe acute respiratory syndrome}',
              '{face mask} AND {severe acute respiratory syndrome}',
              '{face-mask} AND {severe acute respiratory syndrome}',
              '{N95 respirator} AND {severe acute respiratory syndrome}',
              '{FFP1} AND {severe acute respiratory syndrome}',
              '{FFP2} AND {severe acute respiratory syndrome}',
              '{FFP3} AND {severe acute respiratory syndrome}',
              '{surgical mask} AND {severe acute respiratory syndrome}',
              '{surgical grade masks} AND {severe acute respiratory syndrome}',
              '{single-use mask} AND {severe acute respiratory syndrome}',
              '{paper mask} AND {severe acute respiratory syndrome}',
              '{cloth mask} AND {severe acute respiratory syndrome}',
              '{face covering} AND {severe acute respiratory syndrome}',
              'facemask AND {middle east respiratory syndrome}',
              '{face mask} AND {middle east respiratory syndrome}',
              '{face-mask} AND {middle east respiratory syndrome}',
              '{N95 respirator} AND {middle east respiratory syndrome}',
              '{FFP1} AND {middle east respiratory syndrome}',
              '{FFP2} AND {middle east respiratory syndrome}',
              '{FFP3} AND {middle east respiratory syndrome}',
              '{surgical mask} AND {middle east respiratory syndrome}',
              '{surgical grade masks} AND {middle east respiratory syndrome}',
              '{single-use mask} AND {middle east respiratory syndrome}',
              '{paper mask} AND {middle east respiratory syndrome}',
              '{cloth mask} AND {middle east respiratory syndrome}',
              '{face covering} AND {middle east respiratory syndrome}',
              'facemask AND {social distancing}',
              '{face mask} AND {social distancing}',
              '{face-mask} AND {social distancing}',
              '{N95 respirator} AND {social distancing}',
              '{FFP1} AND {social distancing}',
              '{FFP2} AND {social distancing}',
              '{FFP3} AND {social distancing}',
              '{surgical mask} AND {social distancing}',
              '{surgical grade masks} AND {social distancing}',
              '{single-use mask} AND {social distancing}',
              '{paper mask} AND {social distancing}',
              '{cloth mask} AND {social distancing}',
              '{face covering} AND {social distancing}',
              'facemask AND {social isolation}',
              '{face mask} AND {social isolation}',
              '{face-mask} AND {social isolation}',
              '{N95 respirator} AND {social isolation}',
              '{FFP1} AND {social isolation}',
              '{FFP2} AND {social isolation}',
              '{FFP3} AND {social isolation}',
              '{surgical mask} AND {social isolation}',
              '{surgical grade masks} AND {social isolation}',
              '{single-use mask} AND {social isolation}',
              '{paper mask} AND {social isolation}',
              '{cloth mask} AND {social isolation}',
              '{face covering} AND {social isolation}']
